run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec
    - prealloc
    - bodyclose
    - noctx
    - gocritic
    - revive
    - whitespace
    - copyloopvar

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/ihsanmokhlisse/gitopsi

  misspell:
    locale: US

  gosec:
    excludes:
      - G104
      - G304
      - G301
      - G306
      - G204

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint
      - sloppyReassign

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
        - govet

    - path: internal/templates/
      linters:
        - gosec

    - linters:
        - revive
      text: "should have comment"

    - linters:
        - revive
      text: "package-comments"

    - linters:
        - gocritic
      text: "octalLiteral"

    - linters:
        - errcheck
      text: "viper.BindPFlag"

    - linters:
        - revive
      text: "exported: comment"

    - path: internal/git/
      linters:
        - revive
      text: "stutters"

    - path: internal/git/
      linters:
        - gocritic
      text: "hugeParam"

    - path: internal/git/
      linters:
        - gosimple
      text: "S1039"

    - path: internal/git/
      linters:
        - errcheck
      text: "CombinedOutput"

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
