version: 2

project_name: gitopsi

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: gitopsi
    main: ./cmd/gitopsi
    binary: gitopsi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.Version={{.Version}}
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.Commit={{.Commit}}
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: gitopsi
    repository:
      owner: ihsanmokhlisse
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ihsanmokhlisse/gitopsi
    description: Bootstrap production-ready GitOps repositories
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/gitopsi", "version"
    install: |
      bin.install "gitopsi"

nfpms:
  - id: packages
    package_name: gitopsi
    vendor: ihsanmokhlisse
    homepage: https://github.com/ihsanmokhlisse/gitopsi
    description: Bootstrap production-ready GitOps repositories
    maintainer: ihsanmokhlisse
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

release:
  github:
    owner: ihsanmokhlisse
    name: gitopsi
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## gitopsi v{{.Version}}
    
    Bootstrap production-ready GitOps repositories for Kubernetes, OpenShift, AKS, and EKS.
  footer: |
    ## Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install ihsanmokhlisse/tap/gitopsi
    ```
    
    ### Linux (deb/rpm)
    Download the appropriate package from the assets below.
    
    ### Windows
    Download `gitopsi_{{.Version}}_windows_amd64.zip` and add to PATH.
    
    ### Container
    ```bash
    podman pull ghcr.io/ihsanmokhlisse/gitopsi:{{.Version}}
    ```
