version: 2

project_name: gitopsi

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: gitopsi
    main: ./cmd/gitopsi
    binary: gitopsi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: ihsanmokhlisse
    name: gitopsi
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: gitopsi
    repository:
      owner: ihsanmokhlisse
      name: homebrew-tap
    commit_author:
      name: gitopsi-bot
      email: bot@gitopsi.dev
    homepage: https://github.com/ihsanmokhlisse/gitopsi
    description: CLI tool for bootstrapping GitOps repositories
    license: MIT
    skip_upload: true  # Enable when homebrew-tap repo exists

