version: 2

project_name: gitopsi

before:
  hooks:
    - go mod tidy
    - go mod verify
    - go test -v ./...

builds:
  - id: gitopsi
    main: ./cmd/gitopsi
    binary: gitopsi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.Version={{.Version}}
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.Commit={{.Commit}}
      - -X github.com/ihsanmokhlisse/gitopsi/internal/cli.BuildDate={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - docs/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

sboms:
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: checksum
    output: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: '📚 Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: '🔧 Maintenance'
      regexp: '^.*?(chore|ci|build)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: '🔒 Security'
      regexp: '^.*?security(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - Merge pull request
      - Merge branch

brews:
  - name: gitopsi
    repository:
      owner: ihsanmokhlisse
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/ihsanmokhlisse/gitopsi
    description: Bootstrap production-ready GitOps repositories
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/gitopsi", "version"
    install: |
      bin.install "gitopsi"

nfpms:
  - id: packages
    package_name: gitopsi
    vendor: ihsanmokhlisse
    homepage: https://github.com/ihsanmokhlisse/gitopsi
    description: Bootstrap production-ready GitOps repositories
    maintainer: ihsanmokhlisse
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./docs/
        dst: /usr/share/doc/gitopsi/
        type: tree

release:
  github:
    owner: ihsanmokhlisse
    name: gitopsi
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## 🚀 gitopsi v{{.Version}}
    
    Bootstrap production-ready GitOps repositories for Kubernetes, OpenShift, AKS, and EKS.
    
    ### Security
    - ✅ All binaries are signed with cosign
    - ✅ SBOM (Software Bill of Materials) included
    - ✅ Container images scanned for vulnerabilities
    
  footer: |
    ---
    
    ## 📦 Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install ihsanmokhlisse/tap/gitopsi
    ```
    
    ### Linux (deb)
    ```bash
    curl -LO https://github.com/ihsanmokhlisse/gitopsi/releases/download/v{{.Version}}/gitopsi_{{.Version}}_linux_amd64.deb
    sudo dpkg -i gitopsi_{{.Version}}_linux_amd64.deb
    ```
    
    ### Linux (rpm)
    ```bash
    curl -LO https://github.com/ihsanmokhlisse/gitopsi/releases/download/v{{.Version}}/gitopsi_{{.Version}}_linux_amd64.rpm
    sudo rpm -i gitopsi_{{.Version}}_linux_amd64.rpm
    ```
    
    ### Windows
    Download `gitopsi_{{.Version}}_windows_amd64.zip` from assets and add to PATH.
    
    ### Container
    ```bash
    # Pull from GitHub Container Registry
    docker pull ghcr.io/ihsanmokhlisse/gitopsi:{{.Version}}
    
    # Verify signature
    cosign verify ghcr.io/ihsanmokhlisse/gitopsi:{{.Version}}
    
    # Run
    docker run --rm -v $(pwd):/workspace ghcr.io/ihsanmokhlisse/gitopsi:{{.Version}} init
    ```
    
    ### Verify Binary Signature
    ```bash
    cosign verify-blob --certificate checksums.txt.pem --signature checksums.txt.sig checksums.txt
    ```
    
    ---
    
    **Full Changelog**: https://github.com/ihsanmokhlisse/gitopsi/compare/v{{ .PreviousTag }}...v{{.Version}}
