# markdownlint configuration for gitopsi
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD003/heading-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  br_spaces: 2  # Allow trailing spaces for line breaks
  strict: false

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: false  # Allow tabs in code blocks

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013/line-length - Line length
MD013:
  line_length: 150
  heading_line_length: 100
  code_block_line_length: 200
  code_blocks: false
  tables: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024/no-duplicate-heading - Multiple headings with the same content
MD024:
  siblings_only: true

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: "ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary
    - kbd
    - img
    - sup
    - sub

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading - Emphasis used instead of a heading
MD036: false

# MD040/fenced-code-language - Fenced code blocks should have a language specified
MD040: true

# MD041/first-line-heading - First line in file should be a top level heading
MD041:
  level: 1
  front_matter_title: ""

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  names:
    - gitopsi
    - ArgoCD
    - Kubernetes
    - OpenShift
    - GitHub
    - GitLab
  code_blocks: false

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# MD049/emphasis-style - Emphasis style
MD049:
  style: "asterisk"

# MD050/strong-style - Strong style
MD050:
  style: "asterisk"

