# yamllint configuration for gitopsi
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Line length - allow longer lines for URLs and complex values
  line-length:
    max: 150
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Allow multiple documents in same file
  document-start: disable

  # Truthy values - allow various boolean representations
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Comments - require space after #
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Hyphens
  hyphens:
    max-spaces-after: 1

  # Key duplicates
  key-duplicates: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # New lines
  new-lines:
    type: unix

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false

  # Quoted strings - don't require quotes
  quoted-strings:
    quote-type: any
    required: false





